#!/bin/sh
#
# FTP LOGIN                     #  #  #   For Single Movies/ Episodes  #  #  #
#
HOST='IP-ADRESS'
USER='USERNAME'
PORT='PORT'
read -p "Password: " PASSWORD
#
# FTP Download
#
lftp -u $USER,$PASSWORD -p $PORT $HOST << EOF
set ssl:verify-certificate no
cd /archive/tv-720p-ger/
#cd /archive/x264-1080p-ger/
mirror --directory=Directory Name
bye
EOF
#
# Unrar, rename, copy, delete, chmod
#
find . -iname '*.rar' | while read file; do
 (
   DIRNAME=$(dirname "${file}")
   BASENAME=$(basename "${file}")
   cd "${DIRNAME}"
   unrar x -o- "${BASENAME}"
   NEW=$DIRNAME
   chmod -v 644 *.mkv      
   mv *.mkv  "${NEW}".mkv
   mv *.mkv /home/path/to/RcloneIng/temp/ 
   rm -rf /home/path/to/RcloneIng/"${DIRNAME}"
)
done
#
# Rename File "Filebot"
#
filebot -non-strict -script fn:amc /home/path/to/RcloneIng/temp/*.mkv --output /home/path/to/RcloneIng/temp/ --def @/home/path/to/RcloneIng/filebot$
#
# RClone Files to GSuite
#
rclone copy -v "temp" "GSuiteCrypt:Plex Cloud Crypted/TV-Serien/"
#rclone copy -v "temp" "GSuiteCrypt:Plex Cloud Crypted/x264/"
cd temp
rm -rf *
#
exit
