#!/bin/sh
#
# FTP LOGIN
#
HOST='IP'
USER='Username'
PORT='Port'
read -p "Password: " PASSWORD
#
# FTP Download
#
lftp -u $USER,$PASSWORD -p $PORT $HOST << EOF
set ssl:verify-certificate no
cd path/path/
mirror --directory=path.S01E*/
bye
EOF
#
# Unrar, rename, copy, delete
#
read -p "Destination: " DESTINATION
mkdir $DESTINATION
find . -iname '*.rar' | while read file; do
 (
   DIRNAME=$(dirname "${file}")
   BASENAME=$(basename "${file}")
   cd "${DIRNAME}"
   unrar x "${BASENAME}"
   NEW=$DIRNAME
   mv *.mkv  "${NEW}".mkv
   mv *.mkv /home/USER/$ZIELVERZEICHNIS
   rm -rf /home/USER/"${DIRNAME}"
)
done
exit
