#!/bin/sh
#
# FTP LOGIN
#
HOST='IP-Adress'
USER='Username'
PORT='port'
read -p "Password: " PASSWORD
#
lftp -u $USER,$PASSWORD -p $PORT $HOST << EOF
set ssl:verify-certificate no #When you Server have an self sined certificate
cd /what/ever/you/like/to/download
ls
mirror downloads
bye
EOF
unrar e -r *.rar
exit
